apiVersion: v1
data:
  router-config.json: |+
      {
        "configVersion" : "{{ .Values.build.number }}",
        "server": {
          "apiProcessingTimeout" : "60s"
        },
        "routingDefaults": {
          "streetRoutingTimeout": "5s",
          "numItineraries": 12,
          "transferPenalty": 0,
          "turnReluctance": 1.0,
          "elevatorBoardTime": 90,
          "elevatorBoardCost": 90,
          "elevatorHopTime": 20,
          "elevatorHopCost": 20,
          "bicycle" : {
            "speed" : 5,
            "reluctance" : 5.0,
            "boardCost" : 600,
            "walk" : {
              "reluctance" : 10.0
            },
            "parking" : {
              "cost" : 120
            }
          },
          "car" : {
            "reluctance" : 10,
            "decelerationSpeed" : 2.9,
            "accelerationSpeed" : 2.9,
            "rental" : {
              "dropOffTime" : "120s"
            }
          },
          "walk" : {
            "speed" : 1.3,
            "reluctance" : 4.0,
            "stairsReluctance" : 1.65,
            "boardCost" : 600
          },
          "otherThanPreferredRoutesPenalty": 300,
          "transferSlack": 120,
          // Default slack for any mode is 0 (zero)
          "boardSlackForMode": {
            "AIRPLANE" : "35m"
          },
          "alightSlackForMode": {
            "AIRPLANE" : "15m"
          },
          "transitReluctanceForMode" : {
            "RAIL" : 0.85
          },
          "accessEgress": {
            "maxDurationForMode" : {
              "BIKE_RENTAL": "20m",
              "SCOOTER_RENTAL" : "20m"
            }
          },
          "maxDirectStreetDurationForMode": {
            "CAR": "12h"
          },
          "itineraryFilters" : {
            "transitGeneralizedCostLimit" : {
              "costLimitFunction": "900 + 1.5x",
              "intervalRelaxFactor": 0.75
            },
            "bikeRentalDistanceRatio": 0.3
          },
          "ignoreRealtimeUpdates": false,
          "geoidElevation": false,
          "maxJourneyDuration": "P2DT12H",
          "drivingDirection": "right",
          "transferOptimization": {
            "optimizeTransferWaitTime": true,
            "minSafeWaitTimeFactor": 5.0,
            "backTravelWaitTimeFactor": 1.0,
            "extraStopBoardAlightCostsFactor": 8.0
          }
        },
        "transit": {
          "maxNumberOfTransfers" : 12,
          "dynamicSearchWindow" : {
            "minTransitTimeCoefficient" : 0.5,
            "minWaitTimeCoefficient" : 0.5,
            "minWindow" : "1h",
            "maxWindow" : "5h"
          },
          "stopBoardAlightDuringTransferCost" : {
            "DISCOURAGED" : 1500,
            "ALLOWED" : 75,
            "RECOMMENDED" : 30,
            "PREFERRED" : 0
          }
        },
        "flex": {
          "maxTransferDuration" : "5m",
          "maxFlexTripDuration" : "1h15m"
        },
        "transmodelApi": {
          "hideFeedId" : true
        },
        "timetableUpdates": {
          "purgeExpiredData": true
        }
      }
kind: ConfigMap
metadata:
  name: otp2int-router-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}