apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "graph.builder.labels" . | indent 4 }}
  annotations:
      {{- include "common.annotations" . | indent 4 }}
  name: graph-builder-otp2int
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            prometheus.io/path: /metrics
            prometheus.io/port: "9779"
            prometheus.io/scrape: "true"
          labels:
            {{- include "graph.builder.labels" . | indent 12 }}
        spec:
          serviceAccountName: application
          containers:
          - command:
              - "java"
            args:
              - "-server"
              - "-Xms{{ .Values.cronjobGraphBuilder.resources.xms }}"
              - "-Xmx{{ .Values.cronjobGraphBuilder.resources.xmx }}"
              - "-XX:MaxGCPauseMillis=5000"
              - "-XX:+UseTransparentHugePages"
              - "-XX:+AlwaysPreTouch"
              - "-XX:+UseCompactObjectHeaders"
              - "--add-opens=java.base/java.lang=ALL-UNNAMED"
              - "--add-opens=java.base/java.nio=ALL-UNNAMED"
              - "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
              - "--enable-native-access=ALL-UNNAMED"
              - "--sun-misc-unsafe-memory-access=allow"
              - "-javaagent:/opt/jmx/jmx_prometheus_javaagent.jar=9779:/opt/jmx/config.yaml"
              - "-Dfile.encoding=UTF-8"
              - "-Dlogback.configurationFile=/etc/otp2/logback.xml"
              - "-Dentur.otp.service.name=otp2int-gb"
              - "-jar"
              - "otp-shaded.jar"
              - --loadStreet
              - "/etc/application-config"
              - "--save"
            env:
            - name: TZ
              value: Europe/Oslo
            image: {{ .Values.image.identifier }}
            imagePullPolicy: {{ .Values.cronjobGraphBuilder.imagePullPolicy }}
            livenessProbe:
              failureThreshold: 200
              httpGet:
                path: /metrics
                port: 9779
                scheme: HTTP
              initialDelaySeconds: 300
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 30
            name: graph-builder-otp2int
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: 9779
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 20
            resources:
              limits:
                cpu: "{{ .Values.cronjobGraphBuilder.resources.cpuLimit }}"
                memory: {{ .Values.cronjobGraphBuilder.resources.memLimit }}
              requests:
                cpu: "{{ .Values.cronjobGraphBuilder.resources.cpuRequest }}"
                memory: {{ .Values.cronjobGraphBuilder.resources.memRequest }}
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop: [ "ALL" ]
              seccompProfile:
                type: RuntimeDefault
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
            - mountPath: /etc/otp2/logback.xml
              name: logback-config-volume
              subPath: logback.xml
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: graph-builder-otp2int
            name: application-config
          - configMap:
              defaultMode: 420
              name: otp2int-logback-config
            name: logback-config-volume
      backoffLimit: 1
      ttlSecondsAfterFinished: 86400 #24h
  # the cron job should never run as it is used only as a template for creating new jobs.
  schedule: 0 0 1 1 0
  successfulJobsHistoryLimit: 1
  # the cron job should never run as it is used only as a template for creating new jobs.
  suspend: true