apiVersion: v1
data:
  build-config.json: |+
   {
      "graph": "${GRAPH_URI}"
   }
kind: ConfigMap
metadata:
  name: otp2int-build-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}