apiVersion: v1
data:
  otp-config.json: |+
   {
      "otpFeatures": {
        "ActuatorAPI": true,
        "CostlyAssertions" : false,
        "FlexRouting": {{ .Values.configuration.flexRouting }},
        "FloatingBike": {{ .Values.configuration.floatingBike }},
        "OptimizeTransfers": {{ .Values.configuration.optimizeTransfers }},
        "TransferConstraints": {{ .Values.configuration.transferConstraints }},
        "ParallelRouting": {{ .Values.configuration.parallelRouting }},
        "ReportApi" : true,
        "GoogleCloudStorage": true
      }
   }
kind: ConfigMap
metadata:
  name: otp2int-feature-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
      {{- include "common.annotations" . | indent 4 }}
